-- 1. Escribir un bloque PL/SQL que visualice la empresa, y nombre y apellidos de los gerentes de nuestros proveedores, ordenados por nombre de empresa.

-- Hacerlo mediante una estructura:

--   WHILE

--   LOOP 

--   Cursor FOR..LOOP

DECLARE
CURSOR CONSULTA IS
	   SELECT EMPRESA, APELLIDOS, NOMBRE
	   FROM PROVEEDORES
	   ORDER BY EMPRESA;
	   
REGISTRO CONSULTA%ROWTYPE;
BEGIN
	OPEN CONSULTA;
	FETCH CONSULTA INTO REGISTRO;
	WHILE CONSULTA%FOUND LOOP
		  DBMS_OUTPUT.PUT_LINE(REGISTRO.EMPRESA||' '||REGISTRO.APELLIDOS||' '||REGISTRO.NOMBRE);
		  FETCH CONSULTA INTO REGISTRO;
		  END LOOP;
	CLOSE CONSULTA;
END;
/

DECLARE
CURSOR CONSULTA IS
	   SELECT EMPRESA, APELLIDOS, NOMBRE
	   FROM PROVEEDORES
	   ORDER BY EMPRESA;
	   
REGISTRO CONSULTA%ROWTYPE;
BEGIN
	OPEN CONSULTA;
	LOOP
		FETCH CONSULTA INTO REGISTRO;
		EXIT WHEN CONSULTA%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE(REGISTRO.EMPRESA||' '||REGISTRO.APELLIDOS||' '||REGISTRO.NOMBRE);

	END LOOP;
	CLOSE CONSULTA;
END;
/

DECLARE
CURSOR CONSULTA IS
	   SELECT EMPRESA, APELLIDOS, NOMBRE
	   FROM PROVEEDORES
	   ORDER BY EMPRESA;
	   
EMP PROVEEDORES.EMPRESA%TYPE;
APE PROVEEDORES.APELLIDOS%TYPE;
NOM PROVEEDORES.NOMBRE%TYPE;
BEGIN
	OPEN CONSULTA;
	LOOP
		FETCH CONSULTA INTO EMP, APE, NOM;
		EXIT WHEN CONSULTA%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE(EMP||' '||APE||' '||NOM);

	END LOOP;
	CLOSE CONSULTA;
END;
/
