DECLARE
CURSOR CONSULTA IS
	   SELECT EMPRESA, APELLIDOS, NOMBRE
	   FROM PROVEEDORES
	   ORDER BY EMPRESA;
	   
EMP PROVEEDORES.EMPRESA%TYPE;
APE PROVEEDORES.APELLIDOS%TYPE;
NOM PROVEEDORES.NOMBRE%TYPE;
BEGIN
	OPEN CONSULTA;
	LOOP
		FETCH CONSULTA INTO EMP, APE, NOM;
		EXIT WHEN CONSULTA%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE(EMP||'PRUEBA '||APE||' '||NOM);

	END LOOP;
	CLOSE CONSULTA;
END;
/
