DECLARE
	CURSOR CONSULTA IS
		   SELECT PROVINCIA, DESCRIPCION
		   FROM PROVINCIAS
		   WHERE UPPER(DESCRIPCION) LIKE '%A%';

	CANTIDAD NUMBER(8);
	PRO PROVINCIAS.PROVINCIA%TYPE;
	DES PROVINCIAS.DESCRIPCION%TYPE;
BEGIN
	OPEN CONSULTA;
	FETCH CONSULTA INTO PRO, DES;
	WHILE CONSULTA%FOUND LOOP
		  CANTIDAD := NUMERO_CLI(PRO);
		  IF CANTIDAD > 0 THEN
		  	  DBMS_OUTPUT.PUT_LINE('LAS PROVINCIA DE '||DES||' TIENE '||CANTIDAD||' CLIENTES');
		  ELSE
			  DBMS_OUTPUT.PUT_LINE('LA PROVINCIA DE '||DES||' NO TIENE NINGUN CLIENTE');
		  END IF;
		  FETCH CONSULTA INTO PRO, DES;
	END LOOP;
	CLOSE CONSULTA;
END;
/
