CREATE OR REPLACE PACKAGE BODY MIPAQ_FUN IS
    FUNCTION TOTAL_ALBARANES(DESCR IN PROVINCIAS.DESCRIPCION%TYPE)
    RETURN NUMBER
    IS
        TOTAL NUMBER(10);
    BEGIN
        SELECT COUNT(*) INTO TOTAL
        FROM PROVINCIAS, CLIENTES, ALBARANES
        WHERE PROVINCIAS.PROVINCIA = CLIENTES.PROVINCIA
        AND CLIENTES.CLIENTE = ALBARANES.CLIENTE
        AND PROVINCIAS.DESCRIPCION = DESCR;

        RETURN TOTAL;
    END TOTAL_ALBARANES;

    FUNCTION FACTURADO_CLIENTE(COD IN CLIENTES.CLIENTE%TYPE)
    RETURN NUMBER
    IS
        TOTAL NUMBER(16,2);
    BEGIN
        SELECT NVL(SUM(CANTIDAD * PRECIO * (1 - DESCUENTO / 100)), 0) INTO TOTAL
        FROM CLIENTES, ALBARANES, LINEAS
        WHERE CLIENTES.CLIENTE = ALBARANES.CLIENTE
        AND ALBARANES.ALBARAN = LINEAS.ALBARAN
        AND CLIENTES.CLIENTE = COD;

        RETURN TOTAL;
    END FACTURADO_CLIENTE;
END;
/