CREATE OR REPLACE PROCEDURE DOS_PROVI(PROV1 PROVINCIAS.PROVINCIA%TYPE,
                                        PROV2 PROVINCIAS.PROVINCIA%TYPE,
                                        TOTALPROV1 OUT NUMBER,
                                        TOTALPROV2 OUT NUMBER,
                                        DIF OUT NUMBER)
IS
BEGIN
    IF NOT EXISTE(PROV1) THEN
        DBMS_OUTPUT.PUT_LINE('LA PROVINCIA '|| PROV1 ||' NO EXISTE');
    ELSIF NOT EXISTE(PROV2) THEN
        DBMS_OUTPUT.PUT_LINE('LA PROVINCIA '|| PROV2 ||' NO EXISTE');
    ELSE
        TOTALPROV1 := UN_PROVI(PROV1);
        TOTALPROV2 := UN_PROVI(PROV2);
        IF TOTALPROV1 = -1 OR TOTALPROV2 = -1 THEN
            DBMS_OUTPUT.PUT_LINE('UNA DE LAS PROVINCIAS NO TIENE COMPRAS');
        ELSE
            DIF := ABS(TOTALPROV1 - TOTALPROV2);
            DBMS_OUTPUT.PUT_LINE('TOTAL FACTURADO' || PROV1 || ' ES: '|| TOTALPROV1);
            DBMS_OUTPUT.PUT_LINE('TOTAL FACTURADO' || PROV2 || ' ES: '|| TOTALPROV2);
            DBMS_OUTPUT.PUT_LINE('DIFERENCIA ES:' || DIF);
        END IF;
    END IF;
END DOS_PROVI;
/