CREATE OR REPLACE FUNCTION CLIENARTI(EMP IN CLIENTES.EMPRESA%TYPE)
RETURN NUMBER
IS
TOTAL NUMBER(13);
EXISTE CLIENTES.EMPRESA%TYPE;
BEGIN
	SELECT EMPRESA INTO EXISTE
	FROM CLIENTES
	WHERE EMP = EMPRESA;

	SELECT SUM(NVL(CANTIDAD, 0)) INTO TOTAL
	FROM LINEAS, ALBARANES, CLIENTES
	WHERE CLIENTES.CLIENTE = ALBARANES.CLIENTE
	AND ALBARANES.ALBARAN = LINEAS.ALBARAN
	AND CLIENTES.EMPRESA = EMP;
	

EXCEPTION
	WHEN NO_DATA_FOUND THEN
		 DBMS_OUTPUT.PUT_LINE('NO HAY NINGUN CLIENTE CON ESA EMPRESA');
		 TOTAL := -1;
		 RETURN TOTAL;

	WHEN TOO_MANY_ROWS THEN
		 DBMS_OUTPUT.PUT_LINE('HAY MAS DE UN CLIENTE CON ESA EMPRESA');
 		 TOTAL := -2;
		 RETURN TOTAL;

END CLIENARTI;
/
