CREATE OR REPLACE TRIGGER SUPER_TRIGGER
AFTER INSERT
ON PROVINCIAS
FOR EACH ROW

BEGIN

DBMS_OUTPUT.PUT_LINE('Nueva provincia'|| TO_CHAR(:NEW.PROVINCIA)||'-'||:NEW.DESCRIPCION);

END SUPER_TRIGGER;
/
