CREATE OR REPLACE TRIGGER AUDITAR1
AFTER INSERT OR DELETE
ON MIS_CLIENTES
FOR EACH ROW

DECLARE
	MENSAJE VARCHAR2(200);
	INSERBORRA VARCHAR2(20);
BEGIN
	IF INSERTING THEN
	   	 MENSAJE := TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'||:NEW.CLIENTE||:NEW.EMPRESA);
		 INSERBORRA := TO_CHAR('INSERCION');
	ELSIF DELETING THEN			--PODEMOS PONER ELSE TAMBIEN PORQUE ARRIBA LE PONEMOS LO DE AFTER INSERT OR DELETE
		MENSAJE := TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'||:OLD.CLIENTE||:OLD.EMPRESA);
		INSERBORRA := TO_CHAR('BORRADO');
	END IF;

	INSERT INTO AUDITAR_CLI
	VALUES(MENSAJE, INSERBORRA);

	DBMS_OUTPUT.PUT_LINE(MENSAJE||' '||INSERBORRA);
EXCEPTION
	WHEN OTHERS THEN
		 DBMS_OUTPUT.PUT_LINE(SQLCODE||SQLERRM);
	
END;
/
