CREATE OR REPLACE TRIGGER AUDITAR2
AFTER UPDATE
ON MIS_CLIENTES
FOR EACH ROW

DECLARE
	FECHA VARCHAR2(30);
	MENSAJE VARCHAR2(200);
	MODIFICADO VARCHAR2(20) := 'MODIFICACION';
BEGIN
	IF UPDATING THEN
	    MENSAJE := TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:SS:MIN CLIENTE '||:NEW.CLIENTE||' ==> '||:OLD.CLIENTE||' EMPRESA '||:NEW.EMPRESA||' ==> '||:OLD.EMPRESA);
	END IF;

	INSERT INTO AUDITAR_CLI
	VALUES(MENSAJE, MODIFICADO);

EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE(SQLCODE||' '||SQLERRM);
END;
