-- 1.    Crear un procedimiento de nombre PROM_PRECIO que por cada proveedor muestre el promedio del precio al que nos vende sus artículos

--  Proveedor:  FAGOR

-- Promedio Venta:  360€ 

--             Proveedor:  EROSKI

--                         Promedio Venta:  52€

-- …

-- ·         While

-- ·         Loop

CREATE OR REPLACE PROCEDURE PROM_PRECIO
IS
    CURSOR CONSULTA IS
        SELECT EMPRESA, NVL(AVG(PR_VENT), 0)
        FROM PROVEEDORES, ARTICULOS
        WHERE ARTICULOS.PROVEEDOR = PROVEEDORES.PROVEEDOR
        GROUP BY EMPRESA;
    
    EMPRESA PROVEEDORES.EMPRESA%TYPE;
    PROMEDIO NUMBER(12,2);
BEGIN
    OPEN CONSULTA;
    FETCH CONSULTA INTO EMPRESA, PROMEDIO;
    WHILE CONSULTA%FOUND LOOP
        DBMS_OUTPUT.PUT_LINE('PROVEEDOR: '|| EMPRESA);
        DBMS_OUTPUT.PUT_LINE('PROMEDIO VENTA: '|| PROMEDIO || '€');

        FETCH CONSULTA INTO EMPRESA, PROMEDIO;
    END LOOP;
    CLOSE CONSULTA;
END PROM_PRECIO;
/

CREATE OR REPLACE PROCEDURE PROM_PRECIO
IS
    CURSOR CONSULTA IS
        SELECT EMPRESA
        FROM PROVEEDORES
        FOR UPDATE;
    
    EMP PROVEEDORES.EMPRESA%TYPE;
    PRO NUMBER(12,2);
BEGIN
    OPEN CONSULTA;
    FECTH CONSULTA INTO EMP;
    WHILE CONSULTA%FOUND THEN
        SELECT NVL(AVG(PR_VENT), 0) INTO PROMEDIO
        FROM ARTICULOS
        WHERE CURRENT OF;

        DBMS_OUTPUT.PUT_LINE('PROVEEDOR: '|| EMPRESA);
        DBMS_OUTPUT.PUT_LINE('PROMEDIO VENTA: '|| PRO || '€');
    END LOOP;
    CLOSE CONSULTA;
END PROM_PRECIO;

CREATE OR REPLACE PROCEDURE PROM_PRECIO
IS
    CURSOR CONSULTA IS
        SELECT EMPRESA, AVG(PR_VENT) PROMEDIO
        FROM PROVEEDORES, ARTICULOS
        WHERE PROVEEDORES.PROVEEDOR = ARTICULOS.PROVEEDOR
        GROUP BY EMPRESA;

    FILA CONSULTA%ROWTYPE;
BEGIN
    OPEN CONSULTA;
    LOOP
        FETCH CONSULTA INTO FILA;
        EXIT WHEN CONSULTA%NOTFOUND
            DBMS_OUTPUT.PUT_LINE('PROVEEDOR: ' || FILA.EMPRESA);
            DBMS_OUTPUT.PUT_LINE('PROMEDIO VENTA: ' || FILA.PROMEDIO || '€');
    END LOOP;
    CLOSE CONSULTA;
END PROM_PRECIO;



BEGIN
    PROM_PRECIO;
END;
/