DECLARE
CURSOR MI_CURSOR IS
	   SELECT PROVINCIA, DESCRIPCION, PREFIJO
	   FROM PROVINCIAS;
X PROVINCIAS.PROVINCIA%TYPE;
Y PROVINCIAS.DESCRIPCION%TYPE;
Z PROVINCIAS.PREFIJO%TYPE;
BEGIN
	OPEN MI_CURSOR;
	FETCH MI_CURSOR INTO X, Y, Z;
	WHILE MI_CURSOR%FOUND LOOP
		  DBMS_OUTPUT.PUT_LINE('PROV: '||TO_CHAR(X)||' DESCRI: '||Y||' PREF: '||TO_CHAR(Z));
		  FETCH MI_CURSOR INTO X, Y, Z;
	END LOOP;
	CLOSE MI_CURSOR;
END;
/

DECLARE
CURSOR MI_CURSOR IS
	   SELECT *
	   FROM PROVINCIAS;

MIREG MI_CURSOR%ROWTYPE;
BEGIN
	OPEN MI_CURSOR;
	FETCH MI_CURSOR INTO MIREG;
	WHILE MI_CURSOR%FOUND LOOP
		  DBMS_OUTPUT.PUT_LINE('PROV: '||TO_CHAR(MIREG.PROVINCIA)||' DESCRI: '||MIREG.DESCRIPCION||' PREF: '||TO_CHAR(MIREG.PREFIJO));
		  FETCH MI_CURSOR INTO MIREG;
	END LOOP;
	CLOSE MI_CURSOR;
END;
/

DECLARE
CURSOR MI_CURSOR IS
	   SELECT PROVINCIA, DESCRIPCION
	   FROM PROVINCIAS;

MIREG MI_CURSOR%ROWTYPE
BEGIN
	OPEN MI_CURSOR;
	FETCH MI_CURSOR INTO MIREG;
	WHILE MI_CURSOR%FOUND LOOP
		  DBMS_OUTPUT.PUT_LINE('PROV: '||TO_CHAR(MIREG.PROVINCIA)||' DESCRI: '||MIREG.DESCRIPCION);
		  FETCH MI_CURSOR INTO MIREG;
	END LOOP;
	CLOSE MI_CURSOR;
END;
/

