CREATE OR REPLACE PROCEDURE VER_CLIENTES(PRO IN PROVINCIAS.DESCRIPCION%TYPE)
IS
	CURSOR CONSULTA IS
		   SELECT EMPRESA
		   FROM CLIENTES
		   WHERE EXISTS(SELECT *
		   		 		FROM PROVINCIAS
						WHERE PROVINCIAS.PROVINCIA = CLIENTES.PROVINCIA);

BEGIN
	DBMS_OUTPUT.PUT_LINE('LAS SIGUIENTES EMPRESAS DE CLIENTES ESTAN EN '||PRO);
	FOR FILA IN CONSULTA LOOP
		DBMS_OUTPUT.PUT_LINE(FILA.EMPRESA);
	END LOOP;
END VER_CLIENTES;
/
