CREATE OR REPLACE PROCEDURE PROM_PRECIO
IS
	CURSOR CONSULTA IS
		SELECT PROVEEDOR, EMPRESA
		FROM PROVEEDORES;
	CANTIDAD NUMBER(12);
FILA CONSULTA%ROWTYPE;
BEGIN
	OPEN CONSULTA;
	FETCH CONSULTA INTO FILA;
	WHILE SQL%FOUND LOOP
		SELECT NVL(AVG(PR_VENT), 0) INTO CANTIDAD
		FROM ARTICULOS
		WHERE PROVEEDOR = FILA.PROVEEDOR;

		DBMS_OUTPUT.PUT_LINE('EL PROVEEDOR '||FILA.PROVEEDOR);
		DBMS_OUTPUT.PUT_LINE('PROMEDIO VENTA '||CANTIDAD||' €');

		FETCH CONSULTA INTO FILA;
	END LOOP;
	CLOSE CONSULTA;
END PROM_PRECIO;
/
