CREATE OR REPLACE TRIGGER ALTA_PROV
BEFORE INSERT
ON PROVEEDORES
FOR EACH ROW
WHEN(NEW.PROVINCIA IS NOT NULL)

DECLARE
    PRO PROVINCIAS.PROVINCIA%TYPE;
BEGIN
    SELECT PROVINCIA INTO PRO
    FROM PROVEEDORES
    WHERE PROVINCIA = :NEW.PROVINCIA;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        INSERT INTO PROVINCIAS
        VALUES(:NEW.PROVINCIA, 'SIN NOMBRE', 0);
END;